- name: Copying elastic-search repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo
  
- name: Installing Filebeat
  ansible.builtin.dnf:
    name: filebeat
    state: present

- name: Copying filebeat
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Restarting filebeat service
  ansible.builtin.systemd_service:
    name: filebeat
    state: restarted
    enabled: true
    daemon_reload: true