- name: Copying elastic-search repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo
  
- name: Installing Filebeat
  ansible.builtin.dnf:
    name: filebeat
    state: present

# Copy filebeat config
# Start filebeat service