- name: Demo on vars 
  hosts: all                           # host group name 
  vars:
    URL: "play.google.com"
  tasks:
    - name: Printing variables
      ansible.builtin.debug:
        msg: "Value of the url {{ URL }}"
      
