- name: Demo on using shell module 
  hosts: all                                # host group name 
  tasks:
    - name: Running uptime command
      ansible.builtin.shell: uptime
      register: OUT

    - name: Printing uptime output
      ansible.builtin.debug: 
        msg: "{{ OUT }}"
