- name: Demo on errors
  hosts: all                                # host group name 
  tasks:
    - name: Check if java process is running or not 
      ansible.builtin.shell: ps -ef | grep java | grep -v grep

    - name: Printing a message
      ansible.builtin.debug:
        msg: "Hello, World!"