- name: Disabling the default nodejs verison
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enabling nodejs20 verison
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Installing Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Creating {{ appuser }} app user
  ansible.builtin.user:
    name: "{{ appuser }}"

- name: Copying {{ component }} systemd file 
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

# Importing a specific task from common role
- name: Run tasks/other.yaml instead of 'main'
  ansible.builtin.import_role:
    name: common
    tasks_from: pre-req

- name: Installing mysql client
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Installing pre-req package for schema injection
  ansible.builtin.pip:
    name: 
      - PyMySQL
      - cryptography
    executable: pip3.11

- name: Generating {{ component }} artifacts
  community.general.npm:
    path: "{{ app_dir }}"

- name: Download NewRelic Dependencies
  ansible.builtin.shell: "npm install newrelic --save"
  args:
    chdir: /app

- name: Schema Injection
  community.mysql.mysql_db:
    name: all
    state: import
    target: /app/schema/backend.sql 
    login_host: mysql-{{ env }}.clouding-app.shop
    login_user: "{{ secrets.MYSQL_USER }}"
    login_password: "{{ secrets.MYSQL_PASS }}"

- name: Copying rsyslog config
  ansible.builtin.template:
    src: backend.conf
    dest: /etc/rsyslog.d/backend.conf

- name: Restarting rsyslog
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted
    daemon_reload: true

- name: Restarting {{ compomnent }} service
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    daemon_reload: true
