- name: Installing nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: copying nginx proxy file
  ansible.builtin.template:
    src: expense.conf
    dest: "{{ proxy_path }}"

- name: Cleanup of {{ component }} directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: absent

- name: Creating html dir for {{ component }}
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory

- name: Download & extracting {{ component }} code
  ansible.builtin.unarchive:
    src: "{{ url }}"
    dest: "{{ app_dir }}"
    remote_src: yes

- name: Restarting {{ component }} service
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
