- name: Configuring hostname
  ansible.builtin.shell: set-hostname {{ component }}

- name: Installing {{ compomnent }}
  ansible.builtin.package:
    name: mysql-server
    state: present
  
- name: Restarting {{ compomnent }} service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes