compomnent: "mysql"
secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=expense-{{ env }}/data/backend token={{ token }} url=https://vault.clouding-app.shop:8200  validate_certs=False') }}"
appuser: expense
install_filebeat: false